################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../lib/aes128.o \
../lib/autopath.o \
../lib/backtrace.o \
../lib/bitmap.o \
../lib/bond.o \
../lib/bundle.o \
../lib/byteq.o \
../lib/cfm.o \
../lib/classifier.o \
../lib/command-line.o \
../lib/coverage.o \
../lib/csum.o \
../lib/daemon.o \
../lib/dirs.o \
../lib/dpif-linux.o \
../lib/dpif-netdev.o \
../lib/dpif.o \
../lib/dummy.o \
../lib/dynamic-string.o \
../lib/entropy.o \
../lib/fatal-signal.o \
../lib/flow.o \
../lib/hash.o \
../lib/hmap.o \
../lib/hmapx.o \
../lib/json.o \
../lib/jsonrpc.o \
../lib/lacp.o \
../lib/leak-checker.o \
../lib/learn.o \
../lib/learning-switch.o \
../lib/lib_libsflow_a-sflow_agent.o \
../lib/lib_libsflow_a-sflow_poller.o \
../lib/lib_libsflow_a-sflow_receiver.o \
../lib/lib_libsflow_a-sflow_sampler.o \
../lib/list.o \
../lib/lockfile.o \
../lib/mac-learning.o \
../lib/meta-flow.o \
../lib/multipath.o \
../lib/netdev-dummy.o \
../lib/netdev-linux.o \
../lib/netdev-vport.o \
../lib/netdev.o \
../lib/netlink-notifier.o \
../lib/netlink-socket.o \
../lib/netlink.o \
../lib/nx-match.o \
../lib/odp-util.o \
../lib/ofp-errors.o \
../lib/ofp-parse.o \
../lib/ofp-print.o \
../lib/ofp-util.o \
../lib/ofpbuf.o \
../lib/ovsdb-data.o \
../lib/ovsdb-error.o \
../lib/ovsdb-idl.o \
../lib/ovsdb-parser.o \
../lib/ovsdb-types.o \
../lib/packets.o \
../lib/pcap.o \
../lib/poll-loop.o \
../lib/process.o \
../lib/random.o \
../lib/rconn.o \
../lib/reconnect.o \
../lib/route-table.o \
../lib/rtnetlink-link.o \
../lib/sha1.o \
../lib/shash.o \
../lib/signals.o \
../lib/socket-util.o \
../lib/sort.o \
../lib/sset.o \
../lib/stp.o \
../lib/stream-fd.o \
../lib/stream-nossl.o \
../lib/stream-tcp.o \
../lib/stream-unix.o \
../lib/stream.o \
../lib/stress.o \
../lib/string.o \
../lib/svec.o \
../lib/table.o \
../lib/tag.o \
../lib/timer.o \
../lib/timeval.o \
../lib/unicode.o \
../lib/unixctl.o \
../lib/util.o \
../lib/uuid.o \
../lib/vconn-stream.o \
../lib/vconn.o \
../lib/vlan-bitmap.o \
../lib/vlandev.o \
../lib/vlog.o 

C_SRCS += \
../lib/aes128.c \
../lib/autopath.c \
../lib/backtrace.c \
../lib/bitmap.c \
../lib/bond.c \
../lib/bundle.c \
../lib/byteq.c \
../lib/cfm.c \
../lib/classifier.c \
../lib/command-line.c \
../lib/coverage.c \
../lib/csum.c \
../lib/daemon.c \
../lib/dirs.c \
../lib/dpif-linux.c \
../lib/dpif-netdev.c \
../lib/dpif.c \
../lib/dummy.c \
../lib/dynamic-string.c \
../lib/entropy.c \
../lib/fatal-signal.c \
../lib/flow.c \
../lib/hash.c \
../lib/hmap.c \
../lib/hmapx.c \
../lib/json.c \
../lib/jsonrpc.c \
../lib/lacp.c \
../lib/leak-checker.c \
../lib/learn.c \
../lib/learning-switch.c \
../lib/list.c \
../lib/lockfile.c \
../lib/mac-learning.c \
../lib/meta-flow.c \
../lib/multipath.c \
../lib/netdev-dummy.c \
../lib/netdev-linux.c \
../lib/netdev-vport.c \
../lib/netdev.c \
../lib/netlink-notifier.c \
../lib/netlink-socket.c \
../lib/netlink.c \
../lib/nx-match.c \
../lib/odp-util.c \
../lib/ofp-errors.c \
../lib/ofp-parse.c \
../lib/ofp-print.c \
../lib/ofp-util.c \
../lib/ofpbuf.c \
../lib/ovsdb-data.c \
../lib/ovsdb-error.c \
../lib/ovsdb-idl.c \
../lib/ovsdb-parser.c \
../lib/ovsdb-types.c \
../lib/packets.c \
../lib/pcap.c \
../lib/poll-loop.c \
../lib/process.c \
../lib/random.c \
../lib/rconn.c \
../lib/reconnect.c \
../lib/route-table.c \
../lib/rtnetlink-link.c \
../lib/sflow_agent.c \
../lib/sflow_poller.c \
../lib/sflow_receiver.c \
../lib/sflow_sampler.c \
../lib/sha1.c \
../lib/shash.c \
../lib/signals.c \
../lib/socket-util.c \
../lib/sort.c \
../lib/sset.c \
../lib/stp.c \
../lib/stream-fd.c \
../lib/stream-nossl.c \
../lib/stream-ssl.c \
../lib/stream-tcp.c \
../lib/stream-unix.c \
../lib/stream.c \
../lib/stress.c \
../lib/string.c \
../lib/svec.c \
../lib/table.c \
../lib/tag.c \
../lib/timer.c \
../lib/timeval.c \
../lib/unicode.c \
../lib/unixctl.c \
../lib/util.c \
../lib/uuid.c \
../lib/vconn-stream.c \
../lib/vconn.c \
../lib/vlan-bitmap.c \
../lib/vlandev.c \
../lib/vlog.c 

OBJS += \
./lib/aes128.o \
./lib/autopath.o \
./lib/backtrace.o \
./lib/bitmap.o \
./lib/bond.o \
./lib/bundle.o \
./lib/byteq.o \
./lib/cfm.o \
./lib/classifier.o \
./lib/command-line.o \
./lib/coverage.o \
./lib/csum.o \
./lib/daemon.o \
./lib/dirs.o \
./lib/dpif-linux.o \
./lib/dpif-netdev.o \
./lib/dpif.o \
./lib/dummy.o \
./lib/dynamic-string.o \
./lib/entropy.o \
./lib/fatal-signal.o \
./lib/flow.o \
./lib/hash.o \
./lib/hmap.o \
./lib/hmapx.o \
./lib/json.o \
./lib/jsonrpc.o \
./lib/lacp.o \
./lib/leak-checker.o \
./lib/learn.o \
./lib/learning-switch.o \
./lib/list.o \
./lib/lockfile.o \
./lib/mac-learning.o \
./lib/meta-flow.o \
./lib/multipath.o \
./lib/netdev-dummy.o \
./lib/netdev-linux.o \
./lib/netdev-vport.o \
./lib/netdev.o \
./lib/netlink-notifier.o \
./lib/netlink-socket.o \
./lib/netlink.o \
./lib/nx-match.o \
./lib/odp-util.o \
./lib/ofp-errors.o \
./lib/ofp-parse.o \
./lib/ofp-print.o \
./lib/ofp-util.o \
./lib/ofpbuf.o \
./lib/ovsdb-data.o \
./lib/ovsdb-error.o \
./lib/ovsdb-idl.o \
./lib/ovsdb-parser.o \
./lib/ovsdb-types.o \
./lib/packets.o \
./lib/pcap.o \
./lib/poll-loop.o \
./lib/process.o \
./lib/random.o \
./lib/rconn.o \
./lib/reconnect.o \
./lib/route-table.o \
./lib/rtnetlink-link.o \
./lib/sflow_agent.o \
./lib/sflow_poller.o \
./lib/sflow_receiver.o \
./lib/sflow_sampler.o \
./lib/sha1.o \
./lib/shash.o \
./lib/signals.o \
./lib/socket-util.o \
./lib/sort.o \
./lib/sset.o \
./lib/stp.o \
./lib/stream-fd.o \
./lib/stream-nossl.o \
./lib/stream-ssl.o \
./lib/stream-tcp.o \
./lib/stream-unix.o \
./lib/stream.o \
./lib/stress.o \
./lib/string.o \
./lib/svec.o \
./lib/table.o \
./lib/tag.o \
./lib/timer.o \
./lib/timeval.o \
./lib/unicode.o \
./lib/unixctl.o \
./lib/util.o \
./lib/uuid.o \
./lib/vconn-stream.o \
./lib/vconn.o \
./lib/vlan-bitmap.o \
./lib/vlandev.o \
./lib/vlog.o 

C_DEPS += \
./lib/aes128.d \
./lib/autopath.d \
./lib/backtrace.d \
./lib/bitmap.d \
./lib/bond.d \
./lib/bundle.d \
./lib/byteq.d \
./lib/cfm.d \
./lib/classifier.d \
./lib/command-line.d \
./lib/coverage.d \
./lib/csum.d \
./lib/daemon.d \
./lib/dirs.d \
./lib/dpif-linux.d \
./lib/dpif-netdev.d \
./lib/dpif.d \
./lib/dummy.d \
./lib/dynamic-string.d \
./lib/entropy.d \
./lib/fatal-signal.d \
./lib/flow.d \
./lib/hash.d \
./lib/hmap.d \
./lib/hmapx.d \
./lib/json.d \
./lib/jsonrpc.d \
./lib/lacp.d \
./lib/leak-checker.d \
./lib/learn.d \
./lib/learning-switch.d \
./lib/list.d \
./lib/lockfile.d \
./lib/mac-learning.d \
./lib/meta-flow.d \
./lib/multipath.d \
./lib/netdev-dummy.d \
./lib/netdev-linux.d \
./lib/netdev-vport.d \
./lib/netdev.d \
./lib/netlink-notifier.d \
./lib/netlink-socket.d \
./lib/netlink.d \
./lib/nx-match.d \
./lib/odp-util.d \
./lib/ofp-errors.d \
./lib/ofp-parse.d \
./lib/ofp-print.d \
./lib/ofp-util.d \
./lib/ofpbuf.d \
./lib/ovsdb-data.d \
./lib/ovsdb-error.d \
./lib/ovsdb-idl.d \
./lib/ovsdb-parser.d \
./lib/ovsdb-types.d \
./lib/packets.d \
./lib/pcap.d \
./lib/poll-loop.d \
./lib/process.d \
./lib/random.d \
./lib/rconn.d \
./lib/reconnect.d \
./lib/route-table.d \
./lib/rtnetlink-link.d \
./lib/sflow_agent.d \
./lib/sflow_poller.d \
./lib/sflow_receiver.d \
./lib/sflow_sampler.d \
./lib/sha1.d \
./lib/shash.d \
./lib/signals.d \
./lib/socket-util.d \
./lib/sort.d \
./lib/sset.d \
./lib/stp.d \
./lib/stream-fd.d \
./lib/stream-nossl.d \
./lib/stream-ssl.d \
./lib/stream-tcp.d \
./lib/stream-unix.d \
./lib/stream.d \
./lib/stress.d \
./lib/string.d \
./lib/svec.d \
./lib/table.d \
./lib/tag.d \
./lib/timer.d \
./lib/timeval.d \
./lib/unicode.d \
./lib/unixctl.d \
./lib/util.d \
./lib/uuid.d \
./lib/vconn-stream.d \
./lib/vconn.d \
./lib/vlan-bitmap.d \
./lib/vlandev.d \
./lib/vlog.d 


# Each subdirectory must supply rules for building sources it contributes
lib/%.o: ../lib/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/usr/src/linux-headers-2.6.38-11/include -I/usr/src/linux-headers-2.6.38-11/arch/x86/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


